import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "../components/app-sidebar";
import { ThemeProvider } from "./components/theme-provider";
import Head from "next/head";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <>
      <Head>
        <meta name="google" content="notranslate" />
      </Head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <SidebarProvider >
          <AppSidebar />
          <SidebarTrigger />
          {children}
        </SidebarProvider>
        <Toaster />
      </ThemeProvider>
    </>
  );
}
